source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'JSPopView_Example' do
  pod 'JSPopView', :path => '../'
  pod 'KVOController','~> 1.2.0'
  pod 'Masonry',’1.1.0’
  pod 'FSCalendar','2.8.1'
  target 'JSPopView_Tests' do
    inherit! :search_paths

    
  end
end
